# Generated by Django 5.2 on 2026-03-13 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventimage_eventregistration_wishlist_delete_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
